language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t tkonuklar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tkonuklar/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-684975642541"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY